@SampleApi_HostAddress = http://localhost:5175/api/v1

GET {{SampleApi_HostAddress}}/weatherforecast

###---------- 認証↓
### login
POST {{SampleApi_HostAddress}}/Account/Login
Content-Type: application/json

{
    "roleType": "light_user",
    "loginName": "sato",
    "password": "fakepass"
}

### logout
POST {{SampleApi_HostAddress}}/Account/Logout

###
Get {{SampleApi_HostAddress}}/hoge/NoRole

###
Get {{SampleApi_HostAddress}}/hoge/AdminOnly

###
Get {{SampleApi_HostAddress}}/hoge/CheckAdminPolicy

###
Get {{SampleApi_HostAddress}}/hoge/UserOnly

###
Get {{SampleApi_HostAddress}}/hoge/UserOrLightUserOnly


###---------- 認証↑



###
GET {{SampleApi_HostAddress}}/hoge/index

###
GET {{SampleApi_HostAddress}}/hoge/GetName?id=100

###
GET {{SampleApi_HostAddress}}/hoge/GetAge?id=100

###
Post {{SampleApi_HostAddress}}/hoge/GetUser
Content-Type: application/json

{
    "id": 100,
    "name": "a123456",
    "age" : 30
}

########## File Download
###
GET {{SampleApi_HostAddress}}/hoge/GetFile

###
GET {{SampleApi_HostAddress}}/hoge/GetImageFile

###
GET {{SampleApi_HostAddress}}/hoge/GetImageFile?fileName=test-img.jpg

###
GET {{SampleApi_HostAddress}}/hoge/GetCsvFile

########## File Upload
# ファイルを指定すると失敗する
POST {{SampleApi_HostAddress}}/hoge/Upload
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="description"

POWER=TEXT_CONTENTS
--MyBoundary
Content-Disposition: form-data; name="file"; filename="upload1.csv"
Content-Type: text/csv

a,b,c
1,2,3
4,5,6
--MyBoundary--



